

SET(PROJECT_VERSION     "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}-${PROJECT_VERSION_TWEAK}")
                         
MESSAGE("Library : ${PROJECT_NAME}") 
MESSAGE("Version : ${PROJECT_VERSION}")

SET(CMAKE_INSTALL_PREFIX        ${PLATFORM_PACKAGES_PATH})
SET(PUBLIC_INCLUDE_DIRECTORY    ${CMAKE_CURRENT_SOURCE_DIR})

CONFIGURE_FILE(
  "${CMAKE_CURRENT_SOURCE_DIR}/config.h.in"
  "${CMAKE_CURRENT_BINARY_DIR}/config.h"
)
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_BINARY_DIR}")
IF(${CMAKE_CURRENT_SOURCE_DIR} STREQUAL ${CMAKE_SOURCE_DIR})
    INSTALL(FILES "${CMAKE_CURRENT_BINARY_DIR}/config.h" DESTINATION include/${LIBRARY_NAME})
ENDIF()
