
MACRO(SUBDIRPATHS result curdir)
  FILE(GLOB children ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${child})
      LIST(APPEND dirlist ${child})
    ENDIF(IS_DIRECTORY)
  ENDFOREACH(child)
  SET(${result} ${dirlist})
ENDMACRO(SUBDIRPATHS)

SET(PROJECT_VERSION     "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}-${PROJECT_VERSION_TWEAK}")
                         
MESSAGE("Firmware : ${PROJECT_NAME}") 
MESSAGE("Version : ${PROJECT_VERSION}")

IF(${USE_ASM_IF_AVAILABLE})
    ENABLE_LANGUAGE(ASM)
ENDIF()

SET(BUILD_INCLUDE_DIR           "${CMAKE_BINARY_DIR}/include")
SET(CMAKE_INSTALL_PREFIX        ${PLATFORM_PACKAGES_PATH})
SET(PUBLIC_INCLUDE_DIRECTORY    ${CMAKE_CURRENT_SOURCE_DIR})

FILE(MAKE_DIRECTORY "${BUILD_INCLUDE_DIR}/drivers")
FILE(MAKE_DIRECTORY "${BUILD_INCLUDE_DIR}/sys")

CONFIGURE_FILE(
  "${CMAKE_CURRENT_SOURCE_DIR}/app/config.h.in"
  "${BUILD_INCLUDE_DIR}/app/config.h"
)
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR} ${BUILD_INCLUDE_DIR} ${INCLUDE_DIRECTORIES})

IF(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/asp")
    SUBDIRLIST(SUBDIRS ${MY_CURRENT_DIR})
    INCLUDE_DIRECTORIES(${SUBDIRS} ${INCLUDE_DIRECTORIES})
    ADD_SUBDIRECTORY(asp)
ELSE()
    INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}/bsp" ${INCLUDE_DIRECTORIES})
    ADD_SUBDIRECTORY(bsp)
ENDIF()

ADD_SUBDIRECTORY(sys)
ADD_SUBDIRECTORY(app)

ADD_SUBDIRECTORY(doc)
ADD_SUBDIRECTORY(resources)

