

SET(PROJECT_VERSION     "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}-${PROJECT_VERSION_TWEAK}")
                         
MESSAGE("Firmware : ${PROJECT_NAME}") 
MESSAGE("Version : ${PROJECT_VERSION}")

SET(BUILD_INCLUDE_DIR  ${CMAKE_BINARY_DIR}/include)

SET(CMAKE_INSTALL_PREFIX        ${PLATFORM_PACKAGES_PATH})
SET(PUBLIC_INCLUDE_DIRECTORY    ${CMAKE_CURRENT_SOURCE_DIR})

FILE(MAKE_DIRECTORY ${BUILD_INCLUDE_DIR}/bsp/drivers)
FILE(MAKE_DIRECTORY ${BUILD_INCLUDE_DIR}/sys)

CONFIGURE_FILE(
  "${CMAKE_CURRENT_SOURCE_DIR}/app/config.h.in"
  "${BUILD_INCLUDE_DIR}/app/config.h"
)
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR} ${BUILD_INCLUDE_DIR} ${INCLUDE_DIRECTORIES})
