
MACRO(add_image VAR SOURCE FORMAT BPP ENCODING PIXELTYPE)

    GET_FILENAME_COMPONENT(IMAGE_NAME ${SOURCE} NAME_WE)
    GET_FILENAME_COMPONENT(PARENT_DIR ${CMAKE_CURRENT_SOURCE_DIR} DIRECTORY)
    FILE(RELATIVE_PATH INCLUDE_PREFIX ${CMAKE_SOURCE_DIR} ${PARENT_DIR})
    SET(BUILD_INCLUDE_DIR  ${CMAKE_BINARY_DIR}/include/${INCLUDE_PREFIX})
    
    SET(CONVERT_ARGS "")
    
    IF(NOT ${ENCODING} STREQUAL "")
        SET(CONVERT_ARGS ${CONVERT_ARGS} -e ${ENCODING})
    ENDIF()
    
    SET(EXTRA_ARGS  ${ARGN})
    LIST(LENGTH EXTRA_ARGS NUM_EXTRA_ARGS)
    IF(NUM_EXTRA_ARGS GREATER 0)
        SET(CONVERT_ARGS ${CONVERT_ARGS} -x ${ARGV6})
    ENDIF()
    IF(NUM_EXTRA_ARGS GREATER 1)
        SET(CONVERT_ARGS ${CONVERT_ARGS} -y ${ARGV7})
    ENDIF()
    
    ADD_CUSTOM_COMMAND(
        COMMAND convert-image ${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE}
                -o ${CMAKE_CURRENT_BINARY_DIR} --format ${FORMAT}
                --incdir ${BUILD_INCLUDE_DIR} ${CONVERT_ARGS}
        DEPENDS ${SOURCE}
        OUTPUT  ${CMAKE_CURRENT_BINARY_DIR}/${IMAGE_NAME}.c 
                ${CMAKE_CURRENT_BINARY_DIR}/${IMAGE_NAME}.h
                ${BUILD_INCLUDE_DIR}/${IMAGE_NAME}.h
        COMMENT "Generating code for ${IMAGE_NAME}."
    )
    MESSAGE("Image : ${IMAGE_NAME} ${FORMAT} ${ENCODING}")
    SET(${VAR} ${${VAR}} ${IMAGE_NAME}.c)

ENDMACRO()
