
MACRO(add_image VAR SOURCE FORMAT BPP ENCODING PIXELTYPE)

    GET_FILENAME_COMPONENT(IMAGE_NAME ${SOURCE} NAME_WE)
    GET_FILENAME_COMPONENT(PARENT_DIR ${CMAKE_CURRENT_SOURCE_DIR} DIRECTORY)
    FILE(RELATIVE_PATH INCLUDE_PREFIX ${CMAKE_SOURCE_DIR} ${PARENT_DIR})
    SET(BUILD_INCLUDE_DIR  ${CMAKE_BINARY_DIR}/include/${INCLUDE_PREFIX})

    ADD_CUSTOM_COMMAND(
        COMMAND convert-image ${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE}
                -o ${CMAKE_CURRENT_BINARY_DIR} --format ${FORMAT}
                --incdir ${BUILD_INCLUDE_DIR} ${ENCODING} ${PIXELTYPE}
        DEPENDS ${SOURCE}
        OUTPUT  ${CMAKE_CURRENT_BINARY_DIR}/${IMAGE_NAME}.c 
                ${CMAKE_CURRENT_BINARY_DIR}/${IMAGE_NAME}.h
                ${BUILD_INCLUDE_DIR}/${IMAGE_NAME}.h
        COMMENT "Generating code for ${IMAGE_NAME}."
    )
    
    SET(${VAR} ${${VAR}} ${IMAGE_NAME}.c)

ENDMACRO()
