

SET(PROJECT_VERSION     "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}-${PROJECT_VERSION_TWEAK}")
                         
MESSAGE("Library : ${PROJECT_NAME} ${PROJECT_VERSION}") 

IF(CMAKE_TOOLCHAIN_FILE)
    # This is a cross-platform build, and therefore is assumed to be intended for an 
    # embedded target
    SET(CMAKE_INSTALL_PREFIX        ${PLATFORM_PACKAGES_PATH})
    SET(PUBLIC_INCLUDE_DIRECTORY    ${CMAKE_CURRENT_SOURCE_DIR})
    IF(${CMAKE_CURRENT_SOURCE_DIR} STREQUAL ${CMAKE_SOURCE_DIR})
        SET(BUILD_INCLUDE_DIR   ${CMAKE_BINARY_DIR}/include)
        CONFIGURE_FILE(
            "${CMAKE_CURRENT_SOURCE_DIR}/config.h.in"
            "${BUILD_INCLUDE_DIR}/config.h"
        )
        INCLUDE_DIRECTORIES(${BUILD_INCLUDE_DIR} ${INCLUDE_DIRECTORIES})
        INSTALL(FILES "${BUILD_INCLUDE_DIR}/config.h" DESTINATION include/${LIBRARY_NAME})
    ELSE()
        GET_FILENAME_COMPONENT(PARENT_DIR ${CMAKE_CURRENT_SOURCE_DIR} DIRECTORY)
        FILE(RELATIVE_PATH INCLUDE_PREFIX ${CMAKE_SOURCE_DIR} ${PARENT_DIR})
        SET(BUILD_INCLUDE_DIR  ${CMAKE_BINARY_DIR}/include/${INCLUDE_PREFIX})
        EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E create_symlink ${PUBLIC_INCLUDE_DIRECTORY} ${BUILD_INCLUDE_DIR})
        CONFIGURE_FILE(
            "${CMAKE_CURRENT_SOURCE_DIR}/config.h.in"
            "${BUILD_INCLUDE_DIR}/config.h"
        )
        INCLUDE_DIRECTORIES(${BUILD_INCLUDE_DIR} ${INCLUDE_DIRECTORIES})
    ENDIF()
ENDIF(CMAKE_TOOLCHAIN_FILE)
