    

FIND_PACKAGE(SWIG REQUIRED)
INCLUDE(${SWIG_USE_FILE})
    
FIND_PACKAGE(PythonInterp REQUIRED)
FIND_PACKAGE(PythonLibs   REQUIRED)
INCLUDE_DIRECTORIES(${PYTHON_INCLUDE_PATH})
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR})
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DSWIG")
SET(CMAKE_SWIG_FLAGS "")
SWIG_ADD_LIBRARY(${LIBRARY_NAME} LANGUAGE python SOURCES ${SWIG_SOURCES})
SWIG_LINK_LIBRARIES(${LIBRARY_NAME} ${PYTHON_LIBRARIES})
    
# Install PYTHON bindings
EXECUTE_PROCESS(COMMAND python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
                OUTPUT_VARIABLE PYTHON_SITE_PACKAGES OUTPUT_STRIP_TRAILING_WHITESPACE)
INSTALL(TARGETS _${LIBRARY_NAME} DESTINATION ${PYTHON_SITE_PACKAGES}/ebs)
INSTALL(FILES ${TOOLCHAINS_PATH}/resources/python/__init__.py DESTINATION ${PYTHON_SITE_PACKAGES}/ebs)
INSTALL(FILES ${CMAKE_BINARY_DIR}/${LIBRARY_NAME}.py DESTINATION ${PYTHON_SITE_PACKAGES}/ebs)
